name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  requirements:
    name: Install Requirements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Python Requirements
        run: |
          pip install -r requirements/base.txt

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Python Requirements
        run: |
          pip install -r requirements/testing.txt
      - name: Run Tests
        run: pytest

  lint:
    name: Linter Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Python Requirements
        run: |
          pip install -r requirements/linters.txt
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files
